#version 450

#extension GL_GOOGLE_include_directive : enable

#include "LuzCommon.h"

layout(push_constant) uniform _constants {
    VolumetricFogConstants ctx;
};

layout (local_size_x = 10, local_size_y = 10, local_size_z = 8) in;

float PhaseFunction(float cosTheta, float g) {
    float g2 = g * g;
    return (1.0 - g2) / (4.0 * PI * pow(1.0 + g2 - 2.0 * g * cosTheta, 1.5));
}

float SampleShadowMap(LightBlock light, vec3 fragPos) {
    if (light.type == LUZ_LIGHT_TYPE_DIRECTIONAL || light.type == LUZ_LIGHT_TYPE_SUN) {
        vec4 fragInLight = (light.viewProj[0] * vec4(fragPos, 1));
        vec2 baseUV = (fragInLight.xy * 0.5 + vec2(0.5f, 0.5f));
        float shadowDepth = texture(textures[light.shadowMap], baseUV).r;
        return fragInLight.z >= shadowDepth ? 1.0 : 0.0;
    } else {
        vec3 lightToFrag = fragPos - light.position;
        float distanceToReceiver = length(lightToFrag);
        vec3 lightDir = normalize(lightToFrag);
        float shadowDepth = texture(cubeTextures[light.shadowMap], lightDir).r;
        return distanceToReceiver >= (shadowDepth * light.zFar) ? 1.0 : 0.0;
    }
}

vec3 GetWorldPosition(vec3 froxelUVW, float zFar, mat4 proj, mat4 view) {
    vec2 ndcXY = froxelUVW.xy * 2.0 - 1.0;
    float viewZ = froxelUVW.z * zFar;
    vec4 viewPos = vec4(ndcXY * viewZ, -viewZ, 1.0);
    viewPos = inverse(proj) * viewPos;
    vec4 worldPos = inverse(view) * vec4(viewPos.xyz, 1.0);
    return worldPos.xyz;
}

float GetLayerThickness(int layer, vec3 froxelVolumeSize, float zFar, mat4 proj, mat4 view) {
    return zFar / froxelVolumeSize.z;
}

void main() {
    ivec3 gridPos = ivec3(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y, gl_GlobalInvocationID.z);
    if (gridPos.x >= ctx.froxelVolumeSize.x || gridPos.y >= ctx.froxelVolumeSize.y || gridPos.z >= ctx.froxelVolumeSize.z) {
        return;
    }
    
    vec3 worldPos = GetWorldPosition(gridPos.xyz / ctx.froxelVolumeSize, ctx.zFar, scene.proj, scene.view);
    float layerThickness = GetLayerThickness(gridPos.z, ctx.froxelVolumeSize, ctx.zFar, scene.proj, scene.view);
    float dustDensity = ctx.density;
    float scattering = ctx.scattering * dustDensity * layerThickness;
    float absorption = ctx.absorption * dustDensity * layerThickness;

    vec3 viewDir = normalize(worldPos - scene.camPos);
    vec3 lighting = vec3(0.0);

    for (int i = 0; i < scene.numLights; i++) {
        LightBlock light = scene.lights[i];
        if (light.volumetricType != VOLUMETRIC_TYPE_FOG) {
            continue;
        }
        vec3 lightDir = light.direction;
        vec3 lightContribution = light.intensity * light.color;
        if (light.type != LUZ_LIGHT_TYPE_DIRECTIONAL && light.type != LUZ_LIGHT_TYPE_POINT) {
            vec3 lightToFrag = light.position - worldPos;
            lightDir = normalize(lightToFrag);
            lightContribution *= 1.0 / dot(lightToFrag, lightToFrag);
        }
        lighting += lightContribution * PhaseFunction(dot(viewDir, lightDir), ctx.anisotropy) * SampleShadowMap(light, worldPos);
    }

    // lighting *= ctx.albedo;

    vec4 result = vec4(lighting * scattering, scattering + absorption);
    result = vec4(0.001, 0.0, 0.0, 1.0);
    imageStore(images3D[ctx.froxelVolumeRID], gridPos.xyz, result);
}