#version 450

#extension GL_GOOGLE_include_directive : enable

#include "LuzCommon.h"

layout(push_constant) uniform _constants {
    VolumetricFogConstants ctx;
};

layout (local_size_x = 32, local_size_y = 32) in;


vec4 Accumulate(vec4 back, vec4 front) {
    vec3 light = front.rgb + clamp(exp(-front.a), 0.0, 1.0) * back.rgb;
    return vec4(light, front.a + back.a);
}

void Write(ivec3 pixelPos, vec4 value) {
    imageStore(images3D[ctx.froxelVolumeAccumulatedRID], pixelPos, value);
}

void main() {
    ivec2 gridPos = ivec2(gl_GlobalInvocationID.xy);
    if (gridPos.x >= ctx.froxelVolumeSize.x || gridPos.y >= ctx.froxelVolumeSize.y) {
        return;
    }

    vec4 current = vec4(0.0);
    for (int i = 0; i < ctx.froxelVolumeSize.z; i++) {
        vec4 next = imageLoad(images3D[ctx.froxelVolumeRID], ivec3(gridPos.x, gridPos.y, i));
        current = Accumulate(current, next);
        Write(ivec3(gridPos.x, gridPos.y, i), current);
    }
}