name: Ubuntu

on: push
    
env:
  BUILD_TYPE: Release

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install Vulkan SDK
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
        sudo apt update
        sudo apt install vulkan-sdk
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: |
        cd build
        cmake --build .
