name: Ubuntu

on: push
    
env:
  BUILD_TYPE: Release

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Install Vulkan SDK
      run: |
        sudo apt update
        sudo apt install vulkan-sdk xorg-dev
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: |
        cd build
        cmake --build .
